# Generated by Django 2.2.16 on 2023-01-23 10:28

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Category',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, null=True, verbose_name='category_name')),
                ('slug', models.SlugField(editable=False, unique=True, verbose_name='Slug')),
            ],
            options={
                'verbose_name': 'Category',
                'verbose_name_plural': 'Categories',
            },
        ),
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, null=True, verbose_name='prods_name')),
                ('description', models.TextField(null=True)),
                ('price', models.FloatField(null=True)),
                ('discount_price', models.FloatField(default=0)),
                ('material', models.TextField(null=True)),
                ('size', models.IntegerField(null=True)),
                ('created_date', models.DateTimeField(auto_now_add=True, verbose_name='Created Date')),
                ('image_1', models.ImageField(null=True, upload_to='product_images')),
                ('image_2', models.ImageField(null=True, upload_to='product_images')),
                ('category', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='post_category', related_query_name='pcategory', to='product.Category')),
            ],
            options={
                'ordering': ['-id'],
                'verbose_name': 'Product',
                'verbose_name_plural': 'Products',
            },
        ),
    ]
