# Generated by Django 2.2.16 on 2023-01-13 01:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='image_1',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.AddField(
            model_name='product',
            name='image_2',
            field=models.ImageField(null=True, upload_to='product_images'),
        ),
        migrations.DeleteModel(
            name='ProductImage',
        ),
    ]
