# Generated by Django 2.2.16 on 2023-01-23 10:28

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='MyUser',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', models.CharField(max_length=128, verbose_name='password')),
                ('last_login', models.DateTimeField(blank=True, null=True, verbose_name='last login')),
                ('email', models.EmailField(max_length=120, unique=True)),
                ('name', models.CharField(blank=True, max_length=40, null=True, verbose_name='Istifadeci adi')),
                ('surname', models.CharField(blank=True, max_length=40, null=True, verbose_name='Istifadeci soyadi')),
                ('slug', models.SlugField(unique=True)),
                ('activation_code', models.CharField(blank=True, max_length=6, null=True, unique=True)),
                ('password_reset_code', models.CharField(blank=True, max_length=120, null=True)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('is_active', models.BooleanField(default=True)),
                ('is_staff', models.BooleanField(default=False)),
                ('is_superuser', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['-timestamp'],
                'verbose_name': 'MyUser',
                'verbose_name_plural': 'MyUser',
            },
        ),
    ]
